name: Release

on:
  push:
    branches: [master]

jobs:
  # we release if everything is fine
  Release:
    runs-on: ubuntu-latest
    name: Release
    needs: Test
    if: github.event_name == 'push'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: yarn
      - run: yarn build
      - name: Preparing a release 🚀
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          node-version: 14.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
